name: Flutter Build, Release And Deploy

on:
  push:
    branches:
      - develop

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
      - run: flutter pub get
      - run: flutter test

  build_apk:
    name: Generate apk files
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Build apk and Push to Releases
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: flutter build apk --dart-define=CLIENT_ID=${CLIENT_ID} --dart-define=CLIENT_SECRET=${CLIENT_SECRET}
      - name: Upload generated apk to artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.RELEASE_TOKEN }}
