name: Testes e Build APK

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'

      - name: Executar testes
        run: flutter test

  build_apk:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'

      - name: Executar build do APK
        run: flutter build apk
