name: Flutter Build, Release And Deploy
"on":
  push:
    branches:
      - develop
jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
      - run: flutter pub get
#      - run: flutter analyze
      - run: flutter test

  build_apk:
    name: Generate apk files
    needs: [flutter_test]
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Build apk
        run: flutter build apk --split-per-abi --release
      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@master
        with:
          name: app-armeabi-v7a-release
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk