name: Flutter Build, Release And Deploy

on:
  push:
    branches:
      - develop

jobs:
  build_apk:
    name: Generate apk files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Build apk
        run: flutter build apk --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
      - name: Create Tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a v1.0.${{ github.run_number }} -m "Release v1.0.${{ github.run_number }}"
      - name: Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: git push origin --tags
      - name: Upload generated apk to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/*
