name: Flutter Build, Release And Deploy
"on":
  push:
    branches:
      - develop
jobs:
  build_apk:
    name: "Build & Release"
    jobs:
      build:
        name: Build & Release
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - uses: actions/setup-java@v1
            with:
              java-version: "18.x"
          - uses: subosito/flutter-action@v1
            with:
              flutter-version: '3.10.5'
          - run: flutter pub get
          - run: flutter test
          - run: flutter build apk --debug --split-per-abi
          - name: Push to Releases
            uses: ncipollo/release-action@v1
            with:
              artifacts: "build/app/outputs/apk/debug/app-debug.apk"
              tag: v1.0.${{ github.run_number }}
              token: ${{ secrets.TOKEN }}
